### ISSUE TITLE
Setting up auth.json

### ISSUE THREAD

**Issue by JustinWatt** [christerk/ffbclient#34]
Hey. I'd like to checkout the progress of the web client but I'm not sure what values to fill in for the auth.json. I imagine user_id maps to coach id but I'm not sure what goes in client_id and secret. Thanks.

**Comment by christerk** [comment]
user_id should be your coach name.

As for client_id and client_secret, these are OAUTH terms and you can create a pair on the following page on the site: https://fumbbl.com/p/oauth
